services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Activate port 5000 and share it
      # port 5000 is what is used for deployments by default-
      # host machine to container port
      - "${HOST_PORT:-5001}:${CONTAINER_PORT:-5000}"
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - db
    environment:
      # available at runtime
      - PORT=${CONTAINER_PORT:-5000}
      - PYTHONPATH=/app/
    entrypoint: [ "/bin/bash", "/docker-entrypoint.sh" ]
    expose:
      - "${CONTAINER_PORT:-5000}"

  db:
    image: postgres:15
    ports:
      - "5565:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web
    profiles: ["production"]

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    profiles: ["production"]

volumes:
  postgres_data:
