version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env.dev
    environment:
      - PORT=${CONTAINER_PORT:-5000}
      - PYTHONPATH=/app/
    entrypoint: [ "/bin/bash", "/config/docker-entrypoint-dev.sh" ]
    expose:
      - "${CONTAINER_PORT:-5000}"
    networks:
      - red-shell-recruiting_red-shell-recruiting
    ports:
      - "5000:5000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - red-shell-recruiting_red-shell-recruiting

  celery:
    build: .
    entrypoint: ["/docker-entrypoint-celery.sh"]
    depends_on:
      - redis
      - web
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app_admin.settings
    volumes:
      - .:/app
    networks:
      - red-shell-recruiting_red-shell-recruiting

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_local/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_local/certs:/etc/nginx/certs:ro
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - red-shell-recruiting_red-shell-recruiting

volumes:
  postgres_data:
  static_volume:

networks:
  red-shell-recruiting_red-shell-recruiting:
    driver: bridge
