services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Activate port 5000 and share it
      # port 5000 is what is used for deployments by default-
      # host machine to container port
      - "${HOST_PORT:-5001}:${CONTAINER_PORT:-5000}"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    environment:
      # available at runtime
      - PORT=${CONTAINER_PORT:-5000}
      - PYTHONPATH=/app/
    entrypoint: [ "/bin/bash", "/docker-entrypoint.sh" ]
    expose:
      - "${CONTAINER_PORT:-5000}"

  db:
    image: postgres:15
    ports:
      - "5565:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    entrypoint: [""] # override entrypoint inheritance
    command: poetry run celery -A app_admin worker --loglevel=info
    depends_on:
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=app_admin.settings
    volumes:
      - .:/app

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx_local/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
    depends_on:
      - web

volumes:
  postgres_data:
