version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PORT=${CONTAINER_PORT:-5000}
      - PYTHONPATH=/app/
    entrypoint: [ "/bin/bash", "/config/docker-entrypoint-local.sh" ]
    expose:
      - "${CONTAINER_PORT:-5000}"
    networks:
      - red-shell-recruiting_red-shell-recruiting
    ports:
      - "5000:5000"

  db:
    image: postgres:15
    ports:
      - "5565:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-shell-recruiting_red-shell-recruiting

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - red-shell-recruiting_red-shell-recruiting

  celery:
    build: .
    entrypoint: ["/docker-entrypoint-celery.sh"]
    depends_on:
      - redis
      - web
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app_admin.settings
    volumes:
      - .:/app
    networks:
      - red-shell-recruiting_red-shell-recruiting

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx_local/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - red-shell-recruiting_red-shell-recruiting

volumes:
  postgres_data:
  static_volume:

networks:
  red-shell-recruiting_red-shell-recruiting:
    driver: bridge
