services:
  db:
    image: postgres:15
    ports:
      - "5565:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-shell-recruiting_red-shell-recruiting

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - red-shell-recruiting_red-shell-recruiting

  celery:
    build: .
    entrypoint: ["/docker-entrypoint-celery.sh"]
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app_admin.settings
    volumes:
      - .:/app
    networks:
      - red-shell-recruiting_red-shell-recruiting

networks:
  red-shell-recruiting_red-shell-recruiting:
    driver: bridge

volumes:
  postgres_data:
