version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5565:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-shell-recruiting_red-shell-recruiting
