# Generated by Django 4.2.20 on 2025-04-27 05:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_shell_recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='candidate_p_search__6ce400_gin'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='candidate_r_search__f11fd3_gin'),
        ),
    ]
