# Generated by Django 4.2.20 on 2025-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_shell_recruiting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
