# Generated by Django 4.2.20 on 2025-04-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_shell_recruiting', '0002_candidateprofile_search_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_shell_recruiting.resume')),
            ],
            options={
                'db_table': 'resume_processing_log',
                'managed': True,
                'indexes': [models.Index(fields=['resume', 'status'], name='resume_proc_resume__86026f_idx')],
            },
        ),
    ]
