# Generated by Django 4.2.20 on 2025-04-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_shell_recruiting', '0003_resumeprocessinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchVectorProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('profile', 'Candidate Profile')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_shell_recruiting.resume')),
            ],
            options={
                'db_table': 'search_vector_processing_log',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='ResumeProcessingLog',
        ),
        migrations.AddIndex(
            model_name='searchvectorprocessinglog',
            index=models.Index(fields=['resume', 'document_type', 'status'], name='search_vect_resume__f9fdd9_idx'),
        ),
    ]
