# Generated by Django 4.2.20 on 2025-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_shell_recruiting', '0004_searchvectorprocessinglog_delete_resumeprocessinglog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
