# Generated by Django 4.2.20 on 2025-04-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_shell_recruiting', '0005_resume_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
