# Generated by Django 4.2.20 on 2025-05-03 23:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import red_shell_recruiting.models


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0006_alter_candidateprofile_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=red_shell_recruiting.models.document_upload_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="red_shell_recruiting.candidateprofile",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_document",
                "managed": True,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_document"],
                        name="candidate_d_search__d4d0e0_gin",
                    )
                ],
            },
        ),
    ]
