# Generated by Django 4.2.20 on 2025-05-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0007_candidatedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatedocument",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
