# Generated by Django 4.2.20 on 2025-05-04 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0008_candidatedocument_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchvectorprocessinglog",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="red_shell_recruiting.candidatedocument",
            ),
        ),
        migrations.AlterField(
            model_name="searchvectorprocessinglog",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("resume", "Resume"),
                    ("profile", "Candidate Profile"),
                    ("document", "Candidate Document"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="searchvectorprocessinglog",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="red_shell_recruiting.resume",
            ),
        ),
        migrations.AddIndex(
            model_name="searchvectorprocessinglog",
            index=models.Index(
                fields=["document"], name="search_vect_documen_e68a29_idx"
            ),
        ),
    ]
