# Generated by Django 4.2.20 on 2025-05-17 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0010_candidateclientplacement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="candidate_placement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_placement",
                to="red_shell_recruiting.candidateclientplacement",
            ),
        ),
    ]
