# Generated by Django 4.2.20 on 2025-05-17 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0011_alter_candidateprofile_candidate_placement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateclientplacement",
            name="month",
        ),
        migrations.RemoveField(
            model_name="candidateclientplacement",
            name="year",
        ),
        migrations.CreateModel(
            name="CandidatePlacementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_record",
                        to="red_shell_recruiting.candidateprofile",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="red_shell_recruiting.candidateclientplacement",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_placement_history",
                "managed": True,
            },
        ),
    ]
