# Generated by Django 4.2.20 on 2025-05-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0012_remove_candidateclientplacement_month_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CandidatePlacementHistory",
            new_name="CandidateClientPlacementHistory",
        ),
        migrations.RenameModel(
            old_name="Resume",
            new_name="CandidateResume",
        ),
        migrations.AlterModelTable(
            name="candidateclientplacementhistory",
            table="candidate_client_placement_history",
        ),
    ]
