# Generated by Django 4.2.20 on 2025-05-18 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0013_rename_candidateplacementhistory_candidateclientplacementhistory_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfileTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "candidate_profile_title",
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="job_title",
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="red_shell_recruiting.candidateprofiletitle",
            ),
        ),
    ]
