# Generated by Django 4.2.20 on 2025-05-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0014_candidateprofiletitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfileTitleAdmin",
            fields=[
                (
                    "candidateprofiletitle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="red_shell_recruiting.candidateprofiletitle",
                    ),
                ),
            ],
            bases=("red_shell_recruiting.candidateprofiletitle",),
        ),
    ]
