# Generated by Django 4.2.20 on 2025-06-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0016_candidateownership_delete_candidateprofiletitleadmin_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="compensation",
            new_name="compensation_from",
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="compensation_to",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="owner_ship",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="red_shell_recruiting.candidateownership",
            ),
        ),
    ]
