# Generated by Django 4.2.20 on 2025-06-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0017_rename_compensation_candidateprofile_compensation_from_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="owner_ship",
            new_name="ownership",
        ),
    ]
