# Generated by Django 4.2.20 on 2025-06-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0018_rename_owner_ship_candidateprofile_ownership"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="candidate_placement",
            new_name="current_candidate_placement",
        ),
    ]
