# Generated by Django 4.2.20 on 2025-06-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0019_rename_candidate_placement_candidateprofile_current_candidate_placement",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="current_candidate_placement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="currently_active_for",
                to="red_shell_recruiting.candidateclientplacementhistory",
            ),
        ),
    ]
