# Generated by Django 4.2.20 on 2025-06-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0020_alter_candidateprofile_current_candidate_placement",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="current_candidate_placement",
            new_name="candidate_placement_history",
        ),
    ]
