# Generated by Django 4.2.20 on 2025-06-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0021_rename_current_candidate_placement_candidateprofile_candidate_placement_history",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="candidateownership",
            table="candidate_ownership",
        ),
    ]
