# Generated by Django 4.2.20 on 2025-06-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0022_alter_candidateownership_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidateclientplacement",
            options={
                "managed": True,
                "verbose_name": "Candidate Placement",
                "verbose_name_plural": "Candidate Placements",
            },
        ),
        migrations.AlterModelOptions(
            name="candidateclientplacementhistory",
            options={
                "managed": True,
                "verbose_name": "Candidate Placement History",
                "verbose_name_plural": "Candidate Placement Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="candidatedocument",
            options={
                "managed": True,
                "verbose_name": "Candidate Document",
                "verbose_name_plural": "Candidate Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="candidateownership",
            options={
                "managed": True,
                "verbose_name": "Candidate Ownership",
                "verbose_name_plural": "Candidate Ownerships",
            },
        ),
        migrations.AlterModelOptions(
            name="candidateprofile",
            options={
                "managed": True,
                "verbose_name": "Candidate Profile",
                "verbose_name_plural": "Candidate Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="candidateprofiletitle",
            options={
                "managed": True,
                "verbose_name": "Candidate Profile Title",
                "verbose_name_plural": "Candidate Profile Titles",
            },
        ),
        migrations.AlterModelOptions(
            name="candidateresume",
            options={
                "managed": True,
                "verbose_name": "Candidate Resume",
                "verbose_name_plural": "Candidate Resumes",
            },
        ),
        migrations.AlterModelOptions(
            name="searchvectorprocessinglog",
            options={
                "managed": True,
                "verbose_name": "Candidate Vector Processing Log",
                "verbose_name_plural": "Candidate Vector Processing Logs",
            },
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="linkedin_url",
            field=models.URLField(null=True),
        ),
    ]
