# Generated by Django 4.2.20 on 2025-06-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0023_alter_candidateclientplacement_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="red_shell_recruiting.candidateownership",
            ),
        ),
    ]
