# Generated by Django 4.2.20 on 2025-06-07 18:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import red_shell_recruiting.models


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0024_alter_candidateprofile_ownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateCulinaryPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=red_shell_recruiting.models.portfolio_upload_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culinary_portfolios",
                        to="red_shell_recruiting.candidateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Culinary Portfolio",
                "verbose_name_plural": "Candidate Culinary Portfolios",
                "db_table": "candidate_culinary_portfolio",
                "managed": True,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_document"],
                        name="candidate_c_search__45e526_gin",
                    )
                ],
            },
        ),
    ]
