# Generated by Django 4.2.20 on 2025-07-08 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0026_candidateclientplacementhistory_compensation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfileSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Candidate Profile Source",
                "verbose_name_plural": "Candidate Profile Sources",
                "db_table": "candidate_profile_source",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="red_shell_recruiting.candidateprofilesource",
            ),
        ),
    ]
