# Generated by Django 4.2.20 on 2025-07-23 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("red_shell_recruiting", "0027_candidateprofilesource_candidateprofile_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="candidate_placement_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="red_shell_recruiting.candidateclientplacementhistory",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="red_shell_recruiting.candidateprofilesource",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="red_shell_recruiting.candidateprofiletitle",
            ),
        ),
    ]
