# Generated by Django 4.2.20 on 2025-07-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0029_rename_notes_candidateprofile_initial_notes_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="initial_notes",
            new_name="entry_notes",
        ),
    ]
