# Generated by Django 4.2.20 on 2025-08-03 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "red_shell_recruiting",
            "0030_rename_initial_notes_candidateprofile_entry_notes",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="searchvectorprocessinglog",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="red_shell_recruiting.candidateculinaryportfolio",
            ),
        ),
        migrations.AlterField(
            model_name="searchvectorprocessinglog",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("resume", "Resume"),
                    ("profile", "Candidate Profile"),
                    ("document", "Candidate Document"),
                    ("portfolio", "Candidate Portfolio"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="searchvectorprocessinglog",
            index=models.Index(
                fields=["portfolio"], name="search_vect_portfol_29af16_idx"
            ),
        ),
    ]
