# Generated by Django 4.2.20 on 2025-08-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("red_shell_recruiting", "0031_searchvectorprocessinglog_portfolio_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="journalentry",
            table="candidate_journal_entry",
        ),
    ]
